# -*- coding: utf-8 -*-
"""cleancv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192eIr0l13Mjr5BptbydFDHNeKvi6juy9
"""

import pandas as pd
import numpy as np

# Загрузка данных

city = pd.read_excel("city.xlsx")
village = pd.read_excel("village.xlsx")
citydem = pd.read_excel("citydem.xlsx")
villagedem = pd.read_excel("villagedem.xlsx")

tables = {
    "city": city,
    "village": village,
    "citydem": citydem,
    "villagedem": villagedem
}

# Проверка структуры таблиц

for name, df in tables.items():
    print(f"\nТаблица {name}")
    print("Размер:", df.shape)
    print("Типы данных:")
    print(df.dtypes)

# Приведение числовых значений

def clean_numeric_columns(df):
    for col in df.columns:
        if df[col].dtype == object:
            df[col] = (
                df[col]
                .astype(str)
                .str.replace(" ", "", regex=False)
                .str.replace(",", ".", regex=False)
            )
            df[col] = pd.to_numeric(df[col], errors="ignore")
    return df

city = clean_numeric_columns(city)
village = clean_numeric_columns(village)
citydem = clean_numeric_columns(citydem)
villagedem = clean_numeric_columns(villagedem)

# Проверка пропущенных значений

for name, df in tables.items():
    print(f"\nПропуски в таблице {name}:")
    print(df.isna().sum())

city = city.fillna(0)
village = village.fillna(0)
citydem = citydem.fillna(0)
villagedem = villagedem.fillna(0)

# Итоговая проверка

for name, df in tables.items():
    print(f"\nИтоговая информация по {name}:")
    print(df.info())