# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzhR9grS2X8q0vMUYa2osUfuZtmlqRBG
"""

import pandas as pd

# чтение данных
city = pd.read_excel("/content/city.xlsx")
village = pd.read_excel("/content/village.xlsx")
citydem = pd.read_excel("/content/citydem.xlsx")
villagedem = pd.read_excel("/content/villagedem.xlsx")

# базовая информация
print("CITY:")
print(city.shape)
print(city.head(3))
print(city.describe().T)

print("\nVILLAGE:")
print(village.shape)
print(village.head(3))
print(village.describe().T)

print("\nCITYDEM:")
print(citydem)

print("\nVILLAGEDEM:")
print(villagedem)

# проверка пропусков
print("Пропуски CITY:")
print(city.isna().sum().sort_values(ascending=False).head(20))

print("\nПропуски VILLAGE:")
print(village.isna().sum().sort_values(ascending=False).head(20))

# только числовые признаки
city_num = city.select_dtypes(include="number")
village_num = village.select_dtypes(include="number")

print("CITY: корр матрица (первые 10 столбцов):")
print(city_num.corr().iloc[:10, :10])

print("\nVILLAGE: корр матрица (первые 10 столбцов):")
print(village_num.corr().iloc[:10, :10])

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid", font_scale=1.0)

citydem = pd.read_excel("/content/citydem.xlsx")
villagedem = pd.read_excel("/content/villagedem.xlsx")

# аккуратно приводим к числам (если где-то пробелы в тысячах)
for col in ["Прибывшие", "Выбывшие", "Прирост"]:
    citydem[col] = citydem[col].astype(str).str.replace(" ", "").str.replace("–", "-").astype(float)
    villagedem[col] = villagedem[col].astype(str).str.replace(" ", "").str.replace("–", "-").astype(float)

# 1) Столбчатые диаграммы для города
plt.figure(figsize=(10, 5))
city_long = citydem.melt(id_vars="Unnamed: 0",
                         value_vars=["Прибывшие", "Выбывшие", "Прирост"],
                         var_name="Показатель", value_name="Численность")
sns.barplot(data=city_long, x="Unnamed: 0", y="Численность", hue="Показатель")
plt.xlabel("Категория численности городского населённого пункта")
plt.ylabel("Число человек")
plt.title("Город: миграция по категориям численности населённых пунктов")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 2) Столбчатые диаграммы для села
plt.figure(figsize=(10, 5))
village_long = villagedem.melt(id_vars="Unnamed: 0",
                               value_vars=["Прибывшие", "Выбывшие", "Прирост"],
                               var_name="Показатель", value_name="Численность")
sns.barplot(data=village_long, x="Unnamed: 0", y="Численность", hue="Показатель")
plt.xlabel("Категория численности сельского населённого пункта")
plt.ylabel("Число человек")
plt.title("Село: миграция по категориям численности населённых пунктов")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# читаем данные
city = pd.read_excel("/content/city.xlsx")
village = pd.read_excel("/content/village.xlsx")
citydem = pd.read_excel("/content/citydem.xlsx")
villagedem = pd.read_excel("/content/villagedem.xlsx")

# приводим числовые колонки в dem-таблицах
for df in (citydem, villagedem):
    for col in ["Прибывшие", "Выбывшие", "Прирост"]:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace(" ", "")
            .str.replace("–", "-")
            .str.replace(",", ".")
            .astype(float)
        )

# проверяем, что ключ-колонка совпадает
# в обоих случаях это 'Unnamed: 0' — категория населённого пункта
assert set(city["Unnamed: 0"]) == set(citydem["Unnamed: 0"])
assert set(village["Unnamed: 0"]) == set(villagedem["Unnamed: 0"])

# мержим миграционные показатели в основные таблицы
city = city.merge(
    citydem[["Unnamed: 0", "Прибывшие", "Выбывшие"]],
    on="Unnamed: 0",
    how="left"
)
village = village.merge(
    villagedem[["Unnamed: 0", "Прибывшие", "Выбывшие"]],
    on="Unnamed: 0",
    how="left"
)

# таргеты
target_in = "Прибывшие"
target_out = "Выбывшие"

# вспомогательная функция: возвращает X, y по датафрейму
def make_xy(df, target_col):
    # исключаем категорию и сами таргеты
    drop_cols = ["Unnamed: 0", "Прибывшие", "Выбывшие", "Прирост"]  # Прирост только если есть
    drop_cols = [c for c in drop_cols if c in df.columns]
    feature_cols = [c for c in df.columns if c not in drop_cols]
    X = df[feature_cols].select_dtypes(include="number")
    y = df[target_col]
    return X, y

X_city_in, y_city_in = make_xy(city, target_in)
X_city_out, y_city_out = make_xy(city, target_out)

X_vill_in, y_vill_in = make_xy(village, target_in)
X_vill_out, y_vill_out = make_xy(village, target_out)

def top_corr_features(X, y, top_n=10):
    corr = X.corrwith(y).abs().sort_values(ascending=False)
    return corr.head(top_n)

def rf_importance(X, y, top_n=10, random_state=42):
    model = RandomForestRegressor(
        n_estimators=500,
        random_state=random_state,
        n_jobs=-1
    )
    model.fit(X, y)
    imp = pd.Series(model.feature_importances_, index=X.columns)
    return imp.sort_values(ascending=False).head(top_n)

def print_top(title, X, y):
    print(f"\n=== {title}: топ-10 по корреляции ===")
    print(top_corr_features(X, y))
    print(f"\n=== {title}: топ-10 по важности RF ===")
    print(rf_importance(X, y))

# город
print_top("ГОРОД – ПРИБЫВШИЕ", X_city_in, y_city_in)
print_top("ГОРОД – ВЫБЫВШИЕ", X_city_out, y_city_out)

# село
print_top("СЕЛО – ПРИБЫВШИЕ", X_vill_in, y_vill_in)
print_top("СЕЛО – ВЫБЫВШИЕ", X_vill_out, y_vill_out)